[package]
name = "clientcom"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = ["full"] }
net = { path = "../net" }
enc = { path = "../enc" }
anyhow = "1.0.98"
